MovieShopMVC/Controllers/MoviesController.cs
using System;
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
	public class MoviesController : Controller
	{

		// call MovieService
		private readonly IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }



        // method: showing details of the movie
        public async Task<IActionResult> Details(int id)   //input parameter as integer id
		{
            var movie = await _movieService.GetMovieDetails(id);
            return View(movie);
        }


        // method: showing details of the Genre
        public async Task<IActionResult> Genre(int id, int pageSize = 30, int pageNumber = 1)
        {
            // call movie Service and get the data
            var pagedMovies = await _movieService.GetMoviesByGenre(id, pageSize, pageNumber);
            // send pagedMovies info to PagedMovies object
            return View("PagedMovies", pagedMovies);
        }

	}
}

MovieShopMVC/Controllers/UserController.cs
using System;
using System.Security.Claims;
using ApplicationCore.Contracts.Services;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers
{
    [Authorize]  // to make each every method has Filters
    public class UserController : Controller
	{
        // all these action methods should only be execute when user is loged in (using cookie to know if user is loged in)

        private readonly ICurrentLogedInUser _currentLogedInUser;

        private readonly IUserService _userService;

        public UserController(ICurrentLogedInUser currentLogedInUser, IUserService userService)
        {
            _currentLogedInUser = currentLogedInUser;
            _userService = userService;
        }



        [HttpGet]
        // write a code that will check if user is authen (if it is authecticated -> go to cookie and get information)
        // Filters
        //[Authorize]
		public async Task<IActionResult> Purchases(int id, int pageSize = 20, int pageNumber = 1)
        {
            // When we get Cookie back and we can get Cookie here, what should we do here now?
            // go to database and get all the movies purchased by user, user id (so we need to get user id from Cookie)
            // 1. get Cookie from HttpContext
            //var cookie = this.HttpContext.Request.Cookies["MovieShopAuthCookie"];  // based on our debug path (this means our controller object)
            //key for the Cookie
            // 2. decrypted to get user information
            // => we can create a class that exposes HttpContext cookie decrypted info and claims

            // Get UserId to call User Service:
            var userId = _currentLogedInUser.UserId;
            // Use the UserId and send to User Service to get information for that User

            // call User Service and get the data
            var pagedPurchases = await _userService.GetAllPurchasesForUser(id, pageSize, pageNumber);

            // send pagedPurchases info to PagedPurchases object
            return View("PagedPurchases", pagedPurchases);
        }


        [HttpPost]
        public async Task<IActionResult> PurchaseMovie(PurchaseRequestModel model)
        {
            var userId = _currentLogedInUser.UserId;

            // call RegisterUser() method:
            var purchase = await _userService.PurchaseMovie(model, userId);

            // redirect to Purchases page
            return RedirectToAction("Purchases");
        }



        [HttpGet]
		public async Task<IActionResult> Favorites(int id, int pageSize = 20, int pageNumber = 1)
        {
            var userId = _currentLogedInUser.UserId;

            // call User Service and get the data
            var pagedFavorites = await _userService.GetAllFavoritesForUser(id, pageSize, pageNumber);

            // send pagedFavorites info to PagedFavorites object
            return View("PagedFavorites", pagedFavorites);
        }


        [HttpPost]
        public async Task<IActionResult> AddFavorite()
        {
            var userId = _currentLogedInUser.UserId;

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> RemoveFavorite()
        {
            var userId = _currentLogedInUser.UserId;

            return View();
        }



        [HttpGet]
        public async Task<IActionResult> Reviews(int id, int pageSize = 20, int pageNumber = 1)
        {
            var userId = _currentLogedInUser.UserId;

            // call User Service and get the data
            var pagedReviews = await _userService.GetAllReviewsByUser(id, pageSize, pageNumber);

            // send pagedReviews info to PagedReviews object
            return View("PagedReviews", pagedReviews);
        }


        [HttpPost]
        public async Task<IActionResult> UpdateReview()
        {
            var userId = _currentLogedInUser.UserId;

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> DeleteReview()
        {
            var userId = _currentLogedInUser.UserId;

            return View();
        }



        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            var userId = _currentLogedInUser.UserId;

            return View();
        }

	}
}

MovieShopMVC/Views/Shared/Components/Genres/GenresViewComponent.cs
using System;
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Views.Shared.Components.Genres
{
    public class GenresViewComponent : ViewComponent
    {
        private readonly IGenreService _genreService;

        public GenresViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllGenres();
            return View(genres);
        }



    }
}

MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieShopMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @*<li class="nav-link">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="TopRatedMovies">TOP RATED Movies</a>
                        </li>*@

                        @*genres*@
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="dropdownMenuButton1" data-bs-toggle="dropdown">Genres</a>
                            <div class="dropdown-menu">
                                @*call the Genre view component*@
                                @await Component.InvokeAsync("Genres")
                            </div>
                        </li>

                    </ul>

                    @*Login and Register buttons*@
                    @*create partial view*@
                    <partial name="_LoginInfo" />
                       
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
</body>
</html>

MovieShopMVC/Views/Shared/_LoginInfo.cshtml
@using MovieShopMVC.Services

@inject ICurrentLogedInUser currentUser

@if (currentUser.IsAuthenticated)
{
    @*Hide login and Register buttons if user is Authenticated and show User's Full Name, Email and links for Logout and View Profile Pages*@

    <div class="text-end">
        <ul class="nav">
            <li class="nav-item dropdown text-capitalize">

                <a class="nav-link dropdown-toggle" href="#" role="button" id="dropDownProfile" data-bs-toggle="dropdown">
                    @currentUser.FullName
                </a>

                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-controller="User" asp-action="Purchases"> Purchases </a>
                    <a class="dropdown-item" asp-controller="User" asp-action="Favorites"> Favorites </a>
                    <a class="dropdown-item" asp-controller="User" asp-action="Reviews"> Reviews </a>
                    <a class="dropdown-item" asp-controller="User" asp-action="Profile"> View Profile/Account </a>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Logout"> Logout </a>  @*we need Cookie to go back to homepage*@
                </div>

            </li>
        </ul>
    </div>
}
else
{
    @*Show Login and Register buttons if User is not Authenticated
        use this partial view inside the layout Page*@

    <div class="text-end">
        <a class="btn btn-outline-primary me-2" asp-controller="Account" asp-action="Login"> Login </a>
        <a class="btn btn-outline-primary me-2" asp-controller="Account" asp-action="Register"> Register </a>
    </div>
}

MovieShopMVC/Views/Shared/_MovieCard.cshtml
@*Movie Card Partial View will be used across multiple views in our application*@

@model ApplicationCore.Models.MovieCardModel

<div class="card mb-4 shadow">
    @*http://localhost:52342/movies/details/2*@
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
    </a>

</div>

MovieShopMVC/Views/Shared/_Purchase.cshtml
@model ApplicationCore.Models.MovieDetailsModel

@using MovieShopMVC.Services

@inject ICurrentLogedInUser currentUser


@if (currentUser.IsAuthenticated)
{
    // if a user haven't purchased this movie

    <!-- Button trigger modal -->
    <div class="d-grid">

        <button type="button" class="btn btn-outline-secondary btn-block" data-bs-toggle="modal" data-bs-target="#modal1">
            <i class="far fa-edit" aria-hidden="true"></i> REVIEW
        </button>

        <button type="button" class="btn btn-outline-secondary btn-block" data-bs-toggle="modal" data-bs-target="#modal2" href="/User/PurchaseMovie">
            Buy $ @Model.Price
        </button>
    </div>

    <!-- Modal : Purchase -->
    <div>
        <form asp-controller="User" asp-action="PurchaseMovie">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="modal fade" id="modal2" tabindex="-1" aria-labelledby="modal2Label" aria-hidden="true">
                <div class="modal-dialog bg-white">
                    <div>
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="Modal1Label">Confirmation Page</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <partial name="_PurchaseMovie" />
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <input type="submit" class="btn btn-primary" value="Purchase" data-save="modal" />

                            </div>
                            </div>
                    </div>
                </div>
            </div>
        </form>
    </div>



    // if a user has purchased this movie

    <!-- Button trigger modal -->
    @*<div class="d-grid">
            <button type="button" class="btn btn-outline-secondary btn-block" data-bs-toggle="modal" data-bs-target="#modal1">
                <i class="far fa-edit" aria-hidden="true"></i> REVIEW
            </button>

            <button type="button" class="btn btn-outline-secondary btn-block" href="#" target="_blank text-dark">
                Watch Movie
            </button>
        </div>*@

}
else
{
    <!-- Button trigger modal -->
    <div class="d-grid">
        <button type="button" class="btn btn-outline-secondary btn-block" data-bs-toggle="modal" data-bs-target="#modal1">
            <i class="far fa-edit" aria-hidden="true"></i> REVIEW
        </button>

        <button type="button" class="btn btn-outline-secondary btn-block" data-bs-toggle="modal" data-bs-target="#modal2">
            Buy $ @Model.Price
        </button>

    </div>

    <!-- Modal : Review -->
    <div>
        <div class="modal fade" id="modal1" tabindex="-1" aria-labelledby="modal1Label" aria-hidden="true">
            <div class="modal-dialog bg-white">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="Modal1Label">Review:</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="mb-3">
                                <select class="form-select">
                                    <option selected> Rate </option>
                                    <option value="1"> 1 </option>
                                    <option value="1"> 2 </option>
                                    <option value="1"> 3 </option>
                                    <option value="1"> 4 </option>
                                    <option value="1"> 5 </option>
                                    <option value="1"> 6 </option>
                                    <option value="1"> 7 </option>
                                    <option value="1"> 8 </option>
                                    <option value="1"> 9 </option>
                                    <option value="1"> 10 </option>
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="message-text" class="col-form-label"> Please enter your review: </label>
                                <textarea class="form-control" id="message-text"></textarea>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> Close </button>
                        <a class="btn btn-primary" asp-controller="Account" asp-action="Login"> Submit </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal : Purchase -->
    <div>
        <div class="modal fade" id="modal2" tabindex="-1" aria-labelledby="modal2Label" aria-hidden="true">
            <div class="modal-dialog bg-white">
                <div>
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="Modal1Label">Confirmation Page</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p>Please click Purchase button to confirm your purchase.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> Close </button>
                            <a class="btn btn-primary" asp-controller="Account" asp-action="Login"> Purchase </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}